name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: trunk-action
        uses: jetli/trunk-action@v0.4.0
        
      - name: Setup Rust
        run: |
          rustup toolchain install nightly
          rustup override set nightly
          rustup target add wasm32-unknown-unknown
          
      - name: Build Trunk
        run: trunk build --release
          
      
      - name: Deploy to Github Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: dist
